import { z } from 'zod';

/**
 * Schema for one plant catalog entry, stored as `src/data/catalog/plants/<slug>.json`.
 *
 * The prose fields (description, careInstructions, commonProblems, temperature, humidity) are
 * what the UI shows. The `care` block holds the same knowledge as structured values so app
 * logic (fertilization status, repotting advice, weather alerts) can use it without parsing
 * prose. Structured fields are optional while the catalog is being enriched — consumers must
 * fall back when one is missing.
 */

const fahrenheit = z.number().int().min(-40).max(130);
const percent = z.number().int().min(0).max(100);

export const temperatureCareSchema = z
  .object({
    idealMinF: fahrenheit,
    idealMaxF: fahrenheit,
  })
  .refine((t) => t.idealMinF < t.idealMaxF, 'idealMinF must be below idealMaxF');

export const humidityCareSchema = z
  .object({
    minPct: percent,
    maxPct: percent,
  })
  .refine((h) => h.minPct < h.maxPct, 'minPct must be below maxPct');

export const fertilizingCareSchema = z.object({
  /** [min, max] weeks between feedings during the growing season. null = cadence unknown. */
  weeks: z
    .tuple([z.number().int().positive(), z.number().int().positive()])
    .refine(([min, max]) => min <= max, 'weeks must be [min, max]')
    .nullable(),
  /** Product and strength, e.g. "Diluted balanced fertilizer". null = unspecified. */
  fertilizerType: z.string().min(3).nullable(),
  /** The care line this was written from, shown verbatim in the UI */
  tip: z.string().min(1),
});

export const repottingCareSchema = z.object({
  /** Species-specific repotting guidance shown in the repotting dialog */
  tip: z.string().min(1),
});

export const careSchema = z.object({
  temperature: temperatureCareSchema.optional(),
  humidity: humidityCareSchema.optional(),
  fertilizing: fertilizingCareSchema.optional(),
  repotting: repottingCareSchema.optional(),
});

export const toxicityDetailSchema = z.object({
  /** Animals the plant is toxic to. Empty = non-toxic to pets. */
  animals: z.array(z.string().min(1)),
  symptoms: z.array(z.string().min(1)),
  source: z.enum(['plantsm.art']),
});

export const reviewSchema = z.object({
  /**
   * legacy   — hand-written before sourcing was tracked
   * draft    — generated by the enrichment pipeline, awaiting review
   * reviewed — checked by a person against its sources
   */
  status: z.enum(['legacy', 'draft', 'reviewed']),
});

export const catalogEntrySchema = z
  .object({
    name: z.string().min(1),
    botanicalName: z.string().min(1),
    otherNames: z.array(z.string().min(1)).optional(),
    /** Path inside the plant-images bucket, URL-encoded, e.g. "Monstera%20Deliciosa.png" */
    imagePath: z.string().min(1),
    wateringFrequency: z.string().min(1),
    suggestedWateringDays: z.number().int().positive(),
    lightRequirement: z.string().min(1),
    careLevel: z.enum(['Easy', 'Medium', 'Hard']),
    category: z.string().min(1),
    isOutdoorPlant: z.boolean().optional(),
    description: z.string().optional(),
    toxicity: z.string().optional(),
    toxicityDetail: toxicityDetailSchema.optional(),
    temperature: z.string().optional(),
    humidity: z.string().optional(),
    careInstructions: z.array(z.string().min(1)).optional(),
    commonProblems: z.array(z.string().min(1)).optional(),
    care: careSchema.optional(),
    review: reviewSchema,
  })
  .strict();

// With `strict: false`, zod infers tuple elements as optional; restate `weeks` as a pair.
export type FertilizingCare = Omit<z.infer<typeof fertilizingCareSchema>, 'weeks'> & {
  weeks: [number, number] | null;
};
export type PlantCare = Omit<z.infer<typeof careSchema>, 'fertilizing'> & {
  fertilizing?: FertilizingCare;
};
export type CatalogEntry = Omit<z.infer<typeof catalogEntrySchema>, 'care'> & {
  care?: PlantCare;
};
export type ToxicityDetail = z.infer<typeof toxicityDetailSchema>;
